name: Poetry Publish Automaticly

on:
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and publish to pypi
        if: startsWith(github.ref, 'refs/tags')
        uses: JRubics/poetry-publish@v1.9
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}

      - name: Build and publish to testpypi
        if: startsWith(github.ref, 'refs/dev')
        uses: JRubics/poetry-publish@v1.9
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
